-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 10:04:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_simulator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospital_simulator` ;

-- -----------------------------------------------------
-- Schema hospital_simulator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_simulator` DEFAULT CHARACTER SET utf8 ;
USE `hospital_simulator` ;

-- -----------------------------------------------------
-- Table `hospital_simulator`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tiempoTotal` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`enfermeras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`enfermeras` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`enfermeras` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tiempoAtencionMin` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `idPaciente` INT NULL,
  `deiagnostico` ENUM('C') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_e_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospital_simulator`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_e_p_idx` ON `hospital_simulator`.`enfermeras` (`idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`doctores_urgencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`doctores_urgencias` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`doctores_urgencias` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tiempoAtencion` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `idPaciente` INT NULL,
  `diagnostico` ENUM('SR', 'E') NULL DEFAULT NULL,
  `proceso` ENUM('1', '2') NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_du_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospital_simulator`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_du_p_idx` ON `hospital_simulator`.`doctores_urgencias` (`idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`hospital_ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`hospital_ingreso` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`hospital_ingreso` (
  `id` INT NOT NULL,
  `idPaciente` INT NULL DEFAULT NULL,
  `llegadaMin` INT NULL,
  `llegadaAleatorio` FLOAT NULL,
  `diagnostico` ENUM('DA') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_hi_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospital_simulator`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_hi_p_idx` ON `hospital_simulator`.`hospital_ingreso` (`idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`doctores_admision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`doctores_admision` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`doctores_admision` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tiempoAtencion` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `clasificacion` ENUM('G', 'MG', 'L') NULL DEFAULT NULL,
  `idPaciente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_da_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospital_simulator`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_da_p_idx` ON `hospital_simulator`.`doctores_admision` (`idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`sala_radiografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`sala_radiografia` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`sala_radiografia` (
  `id` INT NOT NULL,
  `tiempoEspera` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `idPaciente` INT NULL,
  `diagnostico` ENUM('R') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sr_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospital_simulator`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sr_p_idx` ON `hospital_simulator`.`sala_radiografia` (`idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`radiografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`radiografia` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`radiografia` (
  `id` INT NOT NULL,
  `tiempoAtencionMin` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `diagnostico` ENUM('DU') NULL DEFAULT NULL,
  `idPaciente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_r_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `hospital_simulator`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_r_p_idx` ON `hospital_simulator`.`radiografia` (`idPaciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hospital_simulator`.`simulacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital_simulator`.`simulacion` ;

CREATE TABLE IF NOT EXISTS `hospital_simulator`.`simulacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `min` INT NULL,
  `idDoctorAdmision` INT NULL,
  `idDoctorUrgencia` INT NULL,
  `idEnfermera` INT NULL,
  `idRadiografia` INT NULL,
  `idSalaRadiografia` INT NULL,
  `idIngreso` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_s_hi`
    FOREIGN KEY (`idIngreso`)
    REFERENCES `hospital_simulator`.`hospital_ingreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_da`
    FOREIGN KEY (`idDoctorAdmision`)
    REFERENCES `hospital_simulator`.`doctores_admision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_du`
    FOREIGN KEY (`idDoctorUrgencia`)
    REFERENCES `hospital_simulator`.`doctores_urgencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_e`
    FOREIGN KEY (`idEnfermera`)
    REFERENCES `hospital_simulator`.`enfermeras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_sr`
    FOREIGN KEY (`idSalaRadiografia`)
    REFERENCES `hospital_simulator`.`sala_radiografia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_r`
    FOREIGN KEY (`idRadiografia`)
    REFERENCES `hospital_simulator`.`radiografia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_s_hi_idx` ON `hospital_simulator`.`simulacion` (`idIngreso` ASC) VISIBLE;

CREATE INDEX `fx_s_da_idx` ON `hospital_simulator`.`simulacion` (`idDoctorAdmision` ASC) VISIBLE;

CREATE INDEX `fk_s_du_idx` ON `hospital_simulator`.`simulacion` (`idDoctorUrgencia` ASC) VISIBLE;

CREATE INDEX `fk_s_e_idx` ON `hospital_simulator`.`simulacion` (`idEnfermera` ASC) VISIBLE;

CREATE INDEX `fk_s_sr_idx` ON `hospital_simulator`.`simulacion` (`idSalaRadiografia` ASC) VISIBLE;

CREATE INDEX `fk_s_r_idx` ON `hospital_simulator`.`simulacion` (`idRadiografia` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
