-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 09:35:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tiempoTotal` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfermeras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`enfermeras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`enfermeras` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tiempoAtencionMin` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `idPaciente` INT NULL,
  `deiagnostico` ENUM('C') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_e_p_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_e_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctores_urgencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctores_urgencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctores_urgencias` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tiempoAtencion` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `idPaciente` INT NULL,
  `diagnostico` ENUM('SR', 'E') NULL DEFAULT NULL,
  `proceso` ENUM('1', '2') NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_du_p_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_du_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_ingreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hospital_ingreso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hospital_ingreso` (
  `id` INT NOT NULL,
  `idPaciente` INT NULL DEFAULT NULL,
  `llegadaMin` INT NULL,
  `llegadaAleatorio` FLOAT NULL,
  `diagnostico` ENUM('DA') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hi_p_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_hi_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctores_admision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`doctores_admision` ;

CREATE TABLE IF NOT EXISTS `mydb`.`doctores_admision` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `tiempoAtencion` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `clasificacion` ENUM('G', 'MG', 'L') NULL DEFAULT NULL,
  `idPaciente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_da_p_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_da_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala_radiografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sala_radiografia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sala_radiografia` (
  `id` INT NOT NULL,
  `tiempoEspera` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `idPaciente` INT NULL,
  `diagnostico` ENUM('R') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sr_p_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_sr_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`radiografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`radiografia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`radiografia` (
  `id` INT NOT NULL,
  `tiempoAtencionMin` INT NULL,
  `tiempoAleatorio` FLOAT NULL,
  `diagnostico` ENUM('DU') NULL DEFAULT NULL,
  `idPaciente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_r_p_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_r_p`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`simulacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`simulacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`simulacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `min` INT NULL,
  `idDoctorAdmision` INT NULL,
  `idDoctorUrgencia` INT NULL,
  `idEnfermera` INT NULL,
  `idRadiografia` INT NULL,
  `idSalaRadiografia` INT NULL,
  `idIngreso` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_s_hi_idx` (`idIngreso` ASC) VISIBLE,
  INDEX `fx_s_da_idx` (`idDoctorAdmision` ASC) VISIBLE,
  INDEX `fk_s_du_idx` (`idDoctorUrgencia` ASC) VISIBLE,
  INDEX `fk_s_e_idx` (`idEnfermera` ASC) VISIBLE,
  INDEX `fk_s_sr_idx` (`idSalaRadiografia` ASC) VISIBLE,
  INDEX `fk_s_r_idx` (`idRadiografia` ASC) VISIBLE,
  CONSTRAINT `fk_s_hi`
    FOREIGN KEY (`idIngreso`)
    REFERENCES `mydb`.`hospital_ingreso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_da`
    FOREIGN KEY (`idDoctorAdmision`)
    REFERENCES `mydb`.`doctores_admision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_du`
    FOREIGN KEY (`idDoctorUrgencia`)
    REFERENCES `mydb`.`doctores_urgencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_e`
    FOREIGN KEY (`idEnfermera`)
    REFERENCES `mydb`.`enfermeras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_sr`
    FOREIGN KEY (`idSalaRadiografia`)
    REFERENCES `mydb`.`sala_radiografia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_r`
    FOREIGN KEY (`idRadiografia`)
    REFERENCES `mydb`.`radiografia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
